easy_admin:
    entities:
        Bar:
            class: AppBundle\Entity\Bar
            label: 'Bar'
            form:
                fields:
                    - nom
                    - adresse
                    - description
                    - { property: 'type', type: 'entity', type_options: { class: 'AppBundle:TypeBar'} }
                    - { property: 'creneauhh' , type: 'AppBundle\Form\CreneauhhType'}
                    - { property: 'boisson', type: 'collection', type_options: { entry_type: 'AppBundle:Boisson'}}
                    - { property: 'imageFile', type: 'file'}
                    - { property: 'imageFile2', type: 'file'}
            list:
                actions: ['delete', 'show', '-edit']