easy_admin:
    entities:
        Bar:
            class: AppBundle\Entity\Bar
            label: 'Bar'
            form:
                fields:
                    - nom
                    - adresse
                    - description
                    #- { property: 'typeBar', type: 'easyadmin_autocomplete'}
                    #- { property: 'typeBar', type: 'collection', type_options: { entry_type: 'AppBundle\Form\TypeBarType' }}
                    #- { property: 'creneauhh' , type: 'collection', type_options:{ entry_type: 'AppBundle\Form\CreneauhhType'}}
                    - { property: 'boisson', type: 'collection', type_options: { entry_type: 'AppBundle\Form\BoissonType'}}
                    - { property: 'imageFile', type: 'file'}
                    - { property: 'imageFile2', type: 'file'}
            list:
                actions: ['delete', 'show', '-edit']