easy_admin:
    entities:
        Boisson:
            class: AppBundle\Entity\Boisson
            label: 'Boisson'
            form:
                fields: ['name', 'prixNormal', 'prixHH']
            list:
                actions: ['delete', 'show', '-edit']