easy_admin:
    entities:
        Creneauhh:
            class: AppBundle\Entity\Creneauhh
            label: 'Creneau'
            form:
                fields: ['jour','heureDebut','heureFin']
            list:
                actions: ['delete', 'show', '-edit']