<?php

namespace AppBundle\Repository;

/**
 * CrenauhhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrenauhhRepository extends \Doctrine\ORM\EntityRepository
{
}
