<?php

namespace AppBundle\Repository;

/**
 * CreneauhhRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauhhRepository extends \Doctrine\ORM\EntityRepository
{
}
