<?php

namespace AppBundle\Repository;

/**
 * TypeBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBarRepository extends \Doctrine\ORM\EntityRepository
{
}
